---
before_install:
  - 'eval $(curl https://travis-perl.github.io/init) --auto'
  - 'cpanm --notest App::cpm'
cache:
  directories:
    - '~/perl5'
install:
  - 'AUTHOR_TESTING=0 cpm install --cpanfile cpanfile --workers $(test-jobs) --global --with-recommends --with-suggests --with-configure --with-develop'
  - 'cpan-install --coverage   # installs coverage prereqs, if enabled'
language: perl
matrix:
  include:
    -
      env: COVERAGE=1
      perl: '5.26'
perl:
  - '5.10'
  - '5.12'
  - '5.14'
  - '5.16'
  - '5.18'
  - '5.20'
  - '5.22'
  - '5.24'
  - '5.26'
script:
  - 'prove -lr -j$(test-jobs) t'
sudo: 'false'
